### PR TITLE
Proposed @cmdline decorator to improve DRY in usage

### PR DESCRIPTION
**Pull request by Rosuav**

### CODE REVIEW

**Comment by epsy** [comment]
I'm deciding against this feature for the following reasons:

While it works nicely for one-file projects, it becomes a sanity hazard with larger projects that have multiple modules: Any imports could add commands, at any depth. Two projects which have a CLI and are importable would have to use different "@cmdline" decorators or they would end up mixing their command-line interfaces together because it is tied to a global object, which I've tried to avoid throughout Clize's design. It would also add some complexity to the tests that use it, but that's a minor concern.

The mixup issue can be addressed by having client code always instantiate that collector object, but I still estimate this to be a difficult thing to reason about.  
As it is, the program's entry point calls run with the different parts of the CLI as parameters. If they're spread across different modules, there would be import statements linking their name to where they come from. If it appears in the call to run, it's in the CLI. If not, it isn't. This is very straightforward to reason about.  
Using a "collector decorator" pattern: At the entry point, a method is called. No parameters that indicate what it works upon other than the collector object itself. In the case of a one-module project, it is defined near the top after the imports and then collects things throughout the module. Easy enough, not much can go wrong there. If you upgrade the scenario to multiple modules, several things become not-so-straightforward. If you do something like [what Flask recommends](http://flask.pocoo.org/docs/0.10/patterns/packages/), your package always eagerly imports everything, which can be undesirable. More importantly, it makes it harder to figure out what is included in a CLI from where the CLI endpoint is defined. Each import can have the side effect of adding a command to a CLI. Each import in those imported modules can too. I suppose grep could tell you, but this is more to think about than just reading the entry point code. You can also forget to import things and therefore end up with missing functionality in your CLI, or accidentally cause problematic circular imports. Both of which can be difficult to explain to newcomers.

Keeping it for one-file projects while disrecommending it for larger projects isn't something I want to do.

As you pointed out, if client code really wants it, it can be easily implemented, even if it can be a little repetitive.

In any case, thanks for the pull request and for the opportunity for me to explain this. If there's anything to add on the matter, feel free to discuss it further below.

**Comment by Rosuav** [comment]
No probs. Like a lot of other proposals, this one existed as a means of asking a question and getting a permanently documented answer.

**Comment by smirolo** [comment]
Implicit vs. explicit declaration of what is and what is not part of the CLI interface is a constant battle (ex: see similar ongoing battle between using $PATH or absolute paths to executables).

For all the inconvenience of the implicit approach (well described above) using @cmdline decorators has the advantage of creating a single point of change in the code base. When you have a big team and manage a big code base, "magic" actually trumps anything else. It is well worth the occasional headache. 

Fabric provides ``fabric.decorators.task`` for example. Why is it good for them but not for clize?

I like the ``@cmdline`` feature and upvote it :).

**Comment by Rosuav** [comment]
Like Duff's Device, this example is some sort of argument in this debate, but I'm not sure whether it's for or against.

You have a huge project made up of a bunch modules, including database.py, webservice.py, and utils.py. You add test code to utils.py such that running it will do all your unit testing of that module. You add code to database.py that uses Clize to allow you to call up certain database actions via the back end. Does it make sense to have Clize  Running webservice.py fires up the main server, which (of necessity) imports both the others. Is it right to have Clize "active" for all the database.py functions, when they got imported from webservice?

Pro: It would mean that your main routine could provide functionality from all over the project, very easily, simply by importing stuff that uses the decorator. (Compare how Flask works - you can import Flask from multiple places, get the same `app` object in all of them, and use `@app.route("/")` in one file and `@app.route("/api/blah")` in a completely different file, and the same server then has human-readable and machine-readable endpoints.)

Con: It'd be difficult to consciously separate multiple uses of Clize within one project.

Is it more likely that you'd want a simple way to Clize more than once in a single package, or that you'd want a simple way to Clize something that can be imported from elsewhere?

**Comment by smirolo** [comment]
Good points. The advantages/drawbacks of using a ``@cmdline`` approach are irrelevant from a library standpoint. Some people *will* code a ``@cmdline`` approach on top of Clize because it makes sense in their context. The question is thus: How can Clize make it easy for them to do just that?

Solutions could be:

1. Provide a ``cmdline`` decorator in Clize directly
2. Document a way to hook up a ``cmdline``-style approach into Clize
3. Pass module names to Clize ``run()`` instead of functions and have the logic look for ``@cmdline`` inside those modules. (ex: Django did a great job of making it possible to have random 3rd party app included in your project, all providing command line commands through manage.py).
4. Add a parameter to ``@cmdline`` that specifies the name of the ``__main__`` module under which the command is available (reverse dependency).

**Comment by edk0** [comment]
2 is trivial to do already.

3 mixes ways of finding things unnecessarily: you could pass the name of the module in setuptools entry-point syntax, for example, and not have to iterate over a module's contents. This way, it also hints at being able to add commands without importing their modules, but wouldn't actually enable that.

4 requires that modules are only ever invoked from one __main__, which is not guaranteed to be true

**Pull request closed without merging**
