### PR TITLE
Added hints for keyword args

### PR DESCRIPTION
**Pull request by karanparikh**
Added hints for keyword arguments. This should fix https://github.com/epsy/clize/issues/7

Example - 
```
Karans-MBP:clize karanparikh$ python hello.py karan --halp
hello.py: Unknown option '--halp'. Did you mean '--help'?
Usage: hello.py [OPTIONS] [name]
Karans-MBP:clize karanparikh$ python hello.py karan --no-capitalize
Hello karan!
Karans-MBP:clize karanparikh$ python hello.py karan --no-capitalizee
hello.py: Unknown option '--no-capitalizee'. Did you mean '--no-capitalize'?
Usage: hello.py [OPTIONS] [name]
```

All existing tests pass and I tested my feature manually.

I currently use [editdistance](https://pypi.python.org/pypi/editdistance/0.2) to pick the best keyword argument to use.

### CODE REVIEW

**Comment by epsy** [comment]
Hello and thanks for the patch.

editdistance is a problematic dependency because it is not pure Python. This causes issues with alternate implementations of Python such as PyPy or Jython. In addition, that project has no installable wheels on PyPI, which means the library has to be built when installing. The user may not have a compiler or the right dependencies installed, especially on Windows, which would cause the install to fail. I can't accept that dependency, sorry.

Could difflib be used instead? See https://docs.python.org/3/library/difflib.html#difflib.SequenceMatcher.ratio  
It does pretty much the same as editdistance, except with a different result format.

Other things:

* Please follow PEP8. Some of your lines are over 80 characters.
* For the feature itself, I would suggest moving it to a method of CliSignature instead.
* Consider using the builtin min or max functions instead of a for loop in this case.
* There isn't always going to be a "good" match. You should figure out a threshold for discarding irrelevant guesses. For instance if the only aliases in the signature are ``-h`` and ``--help``, they are still not relevant suggestion if you typed ``--verbose``.
* The final patch will need tests, and I think test-driven development would help with figuring out the right threshold. If you need help figuring out the tests structure let me know. I know they could stand some explaining.
* For backwards-compatibility, errors.UnknownOption(name) should still work. In fact, it could perhaps handle calling the "find the best match" method, since it has access to the CliBoundArguments instance. This also has the effect of leaving the parser loop untouched.

I know my bug description was vague, and so is the guidance for contributing. Sorry about that. I'll work to fix that.

Since I see you're in the area, we can discuss or work on this at SF PMG's Project Night @ Eventbrite Wednesday.

**Comment by karanparikh** [comment]
Thanks for the excellent feedback @epsy! I'll work on addressing your comments. 

Could you please give a few pointers on where to add the tests? I tried modifying `test_parser.py` but couldn't make any progress.

Also, are you suggesting that the "find best match" function be made a part of `CliSignature` and then `UnknownOption` calls this function?

**Comment by epsy** [comment]
On Sun, 17 May 2015 at 10:45 Karan Parikh <notifications@github.com> wrote:

> Thanks for the excellent feedback @epsy <https://github.com/epsy>! I'll
> work on addressing your comments.
>
> Could you please give a few pointers on where to add the tests? I tried
> modifying test_parser.py but couldn't make any progress.
>
Sure. test_parser.SigErrorTests seems like the most appropriate section.
Each tuple in that class whose name that doesn't start with test_ or _ is
run through the sigerrortests function. This makes the tuple format as
follows:

* a string representation of the original function signature, ie. "*, opt"
for a function that takes opt as required keyword argument.
* the input arguments from the command line
* the expected exception, in your case errors.UnknownOption
* the expected value of exc.message

Considering you'll need to repeat tests against the same signature and
exception type, you're better off giving those a short name, ie. in
SigErrorTests:

    _uo = errors.UnknownOption
    _bm_1 = '*, hello'

    bm_1_match = _bm_1, ['--hallo'], _uo, "Unknown option '--hallo', did
you mean '--hello'?"
    bm_1_nomatch = _bm_1, ['--goodbye'], _uo, "Unknown option '--goodbye'?"

.. and so forth. I guess a function could be useful for producing the
messages too.

Also, are you suggesting that the "find best match" function be made a part
> of CliSignature and then UnknownOption calls this function?
>
Yes. UnknownOption should have ba (CliBoundArguments) as attribute by the
time .message is used thanks to SetErrorContext. But you should handle the
case where the attribute is not present, too.

**Comment by karanparikh** [comment]
Thanks! I have most of the changes done. Had a quick question about the expected behavior for the following test case -

```python
    unknown_kw_after_short_flag = (
        '*, o=False', ['-oa'], errors.UnknownOption,
        'Unknown option \'-a\'')
```
Should we suggest `-o` in this case or not?

**Comment by epsy** [comment]
Well, in the case of short options, all of them are equidistant in this
scheme, so it makes little sense to suggest any.

**Comment by karanparikh** [comment]
Makes sense. So basically we should give suggestions only for `OptionParameter`s correct?

**Comment by epsy** [comment]
Not sure I understand your question correctly. The specialized lookup used
in IntOptionParameter and FlagParameter is implemented in NamedParameter
IIRC and only concerns short options. The general lookup is done in the
parser loop (it could perhaps be moved to a method of CliSignature) and
doesn't care about the parameter's type as long as it is in sig.aliases.

**Comment by epsy** [comment]
Great!

Just three things:

* It's fairly unconventional to write a "select the maximum" loop yourself in Python. Can you modify that to be a generator + call to max() ? You can use max's key= argument to only sort on the guess's proximity.
* Make the threshold a class attribute(``guess_opt_threshold``?) so that it can be easily modified on instances or subclasses.
* What's ``s_known_arg = str(known_arg)`` for? Are you programming defensively for if aliases aren't strings? Is it something you encountered? Add a test for that please.

I should be done nitpicking after this :-)

**Comment by epsy** [comment]
In fact, the best guess could be computed with something such as:

```python
closest_alias = max(self.sig.aliases, key=partial(util.compute_similarity, given_opt)
```

**Comment by karanparikh** [comment]
Thanks for the feedback @epsy. It is very helpful :)

I'll address your comments later tonight/tomorrow night and will update the pull request.

**Comment by epsy** [comment]
Oh. No need for three intermediary steps. You can use `closest_match = max(sig.aliases, key=partial(compute_similarity, given_arg))`:

* `sig.aliases` is the data being sorted (iterating over a dict yields keys, thus each alias)
* The `key` function tells max what's used to figure out the order (the proximity)
* Using the `max` function likes so makes the program only process the list once.
* Unfortunately using max that way means we can't filter the bad matches on the spot. We can however just check the final one for good enough proximity afterwards.
* (Oh, and write `self.threshold`. It will map to the class attribute automatically, but also to a subclass or instance attribute if someone overrides it. Naming the class explicitly locks it to that class.)

Don't worry, `max`, `min` and `sort`'s key function trip a lot of people up.

**Comment by karanparikh** [comment]
Hi @epsy 

I think I've addressed all your comments. 

I was able to figure out how your snippet worked by lookup up the documentation for the various Python functions. What I was not able to figure out was filtering w/o an additional call to the `compute_similarity` function. Your explanation was really good though! Thanks for writing that up.

**Comment by epsy** [comment]
Great!

With your permission I'd like to merge this tomorrow into master towards 3.1.

Note that I just changed the copyright notice in each file so I can more easily assign new copyrights (such as yours) in AUTHORS. This doesn't change change much for you, but I'd rather let you check this is OK rather than change the copyright notice behind your back and merge anyway. Feel free to add yourself as contributor (alphabetical order) in AUTHORS in your pull request if you'd like.

**Comment by karanparikh** [comment]
Looks good to me. I will update my fork to pull in your changes, add myself to the AUTHORS file and send out a new diff later tonight.

**Comment by karanparikh** [comment]
@epsy Feel free to merge my changes. Thanks for all the help and feedback.

**Comment by epsy** [comment]
Thanks for your patch and patience :-)

**Pull request merged**
